### ISSUE TITLE
Package is missing the bz2 dependency

### ISSUE THREAD

**Issue by planthaber** [rock-planning/planning-fd_cedalion#1]
planning/fd_cedalion(/data/jenkins/workspace/workspace/rock-incremental/Flavor/master/node/Ubuntu_current/dev/planning/fd_cedalion): failed in build phase
    'make --jobserver-fds=5,6 -j' returned status 2
    see /data/jenkins/workspace/workspace/rock-incremental/Flavor/master/node/Ubuntu_current/dev/install/log/planning/fd_cedalion-build.log for details
    last 10 lines are:

```
/usr/bin/ld: cannot find -lbz2
/usr/bin/ld: cannot find -lbz2
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
src/CMakeFiles/cedalion-search.dir/build.make:2551: recipe for target 'src/libcedalion-search.so' failed
make[2]: *** [src/libcedalion-search.so] Error 1
CMakeFiles/Makefile2:186: recipe for target 'src/CMakeFiles/cedalion-search.dir/all' failed
make[1]: *** [src/CMakeFiles/cedalion-search.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by 2maz** [comment]
Fixed. See also rock-core/rock-package_set#31
